# 使用语言
language: node_js
# node版本
node_js: "12.16.3"

dist: bionic

# 设置只监听哪个分支
branches:
    only:
        - source
# 缓存，可以节省集成的时间
cache:
    apt: true
    directories:
        - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
    - git config --global user.name "luisleee"
    - git config --global user.email "luisleee@126.com"
    - npm install -g hexo-cli
install:
    - npm install
script:
    - hexo clean
    - hexo generate
after_success:
    - cd ./public
    - git init
    - git add --all .
    - git commit -m "Travis CI Auto Builder"
    - git push --force https://$GITHUB_TOKEN@github.com/luisleee/luisleee.github.io.git master
