name: Generate

on:
  push:
    branches:
      - source

jobs:
  build:
    name: Generate blog
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: source

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Setup git
        run: |
          git config --global user.name "luisleee"
          git config --global user.email "luisleee@126.com"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install hexo-cli
        run: |
          npm install -g hexo-cli

      - name: Install dependencies
        run: |
          npm install

      - name: Generate
        run: |
          hexo clean
          hexo generate

      - name: Deploy
        run: |
          cd ./public
          git init
          git add --all .
          git commit -m "Github Actions Auto Builder"
          git push --force https://${{secrets.ACCESS_TOKEN}}@github.com/luisleee/luisleee.github.io.git master
